<?php
/**
 * @var \Amasty\IlyaRog\Block\Form $block
 */
?>
<form class="form" id="myformid" action="<?= $block->getUrl($block->getFormAction()); ?>" method="post" data-mage-init='{"validation":{"rules": {"required":true}}}'>
    <div data-bind="scope:'skuAutocomplete'">
    <!-- ko template : getTemplate() -->
        <!-- /ko -->
    </div>
    <div>
        <?php if ($block->isShowQty()): ?>
        <label>QTY: </label>
            <input type="text" name="qty" id="qtyid" class="required-entry validate-greater-than-zero"  placeholder="<?= $block->getQtyStandart() ?>" />
        <?php endif; ?>
        <?= $block->getChildHtml() ?>
        <button>Отправить</button>
    </div>
</form>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "skuAutocomplete" : {
                        "component": "Amasty_IlyaRog/js/koAutocomplete",
                        "template": "Amasty_IlyaRog/koAutocomplete"
                    }
                }
            }
        }
    }
</script>
